### PR TITLE
feat: add dispute resolution functionality and tests

### LINKED ISSUE #24: smart contract: Create dispute resolution functions
## Description:

Two functions are needed to complete the dispute flow. One of them must be able to change the “dispute_flag” property from false to true, and the second one must be able to return the necessary funds to the client and release the necessary funds to the service provider. The amount of funds returned to the client and released to the service provider is at the discretion of the service resolver (dispute_resolver).

## Change dispute flag:

A function called “change_dispute_flag” must be created in the [contract.rs](https://github.com/Tico4Chain-Coders/Trustless-Work/blob/develop/contracts/engagement/src/contract.rs) file. This function can only be executed by the "dispute_resolver" and it will change the value of the escrow property called “dispute_flag” to true.

### Requirements:

1. This function when executed must automatically change the “dispute_flag” value of the escrow to true.
3. The new value must be stored correctly in the contract escrow.

### Validations:

1. Verify that the escrow has been defined by means of its engagement_id.  Otherwise, this means that the escrow has not been initialized.
2. The property “dispute_flag” must not be previously set to true when executing this function.

### Function parameters:

- *engagement_id (type: String) → Escrow Identifier.*

**Note:** Feel free to add more parameters to the function if necessary.

## Resolving disputes:

The function “**refund_remaining_funds**” of the contract in the file [contract.rs](https://github.com/Tico4Chain-Coders/Trustless-Work/blob/develop/contracts/engagement/src/contract.rs) must be modified. This function currently refunds the client the amount of funds contained in the escrow contract in case the escrow has been cancelled.

This function will now take care of resolving disputes by returning to the client and the service provider a certain amount of funds contained in the contract. The amount of funds to be transferred to both parties is at the discretion of the dispute_resolver.

### Requirements:

1. The name of this function must be changed to “resolving_disputes”.
2. The escrow from which disputes are to be resolved must be identified by means of the engagement id.
3. The amounts should be transferred to the client and the service provider according to what is received by parameters. Since in these parameters you will receive how much will be transferred to each of the parties (client and service provider).

### Validations:

1. Verify that the escrow has been defined by means of its engagement_id.  Otherwise, this means that the escrow has not been initialized.
2. The “dispute_flag” property of the escrow must be previously set to true.
3. Only the “dispute_resolver” should be able to execute this function.
4. The contract must have sufficient balance to transfer the amounts to the client and the service provider.
### Function parameters:

- *engagement_id* (type: String) → Escrow Identifier.*
- *usdc_contract* (type: Address) → usdc contract address, address of the token with which usdc amounts are managed.
- *client_funds* (type: u128) → Amount of funds to be reimbursed to customer.
- *service_provider_funds* (type: u128) → Amount of funds to be released to the service provider

**Note:** Feel free to add more parameters to the function if necessary.

## Errors:

We currently have a number of custom errors which we throw when executing some of the contract functions. An example of the above would be the following:

```rust
if escrow.balance != escrow.amount {
	  return Err(ContractError::EscrowBalanceNotSufficienteToSendEarnings);
}
```

You only need to worry about throwing the error message, you don't need to handle custom errors. So if you need to return an error within the flow due to one of the validations, you can do it as follows:

```rust
if escrow.balance != escrow.amount {
	  return Err("Your error message");
}
```

**You must make sure that the message you are sending as an error is very clear and makes sense as to why the error is being sent.**

## Tests:

In the [test.rs](https://github.com/Tico4Chain-Coders/Trustless-Work/blob/develop/contracts/engagement/src/test.rs) file you must develop the following test to check that the contract flow works correctly together with the functions you have just built:

1. The escrow must be initialized (intialize_escrow).
2. Fund an escrow but not using the “fund_escrow” function of the contract, but doing it directly with the token we created for this type of testing. With this token you will be able to transfer funds to the escrow contract so that they can be claimed by the service provider (the token code can be found in the file called [token.rs](https://github.com/Tico4Chain-Coders/Trustless-Work/blob/develop/contracts/engagement/src/token.rs).
3. Change the value of the property “dispute_flag” to true with the function “change_dispute_flag” and verify that it does it correctly.
4. Execute the function “resolving_disputes” and verify that all the corresponding amounts have been correctly transferred to both the client and the service provider.
5. Verify that all required validations for “dispute_flag” and “change_dispute_flag” are working correctly.

You can rely on the previously created tests to complete your test. The important thing is that you succeed in testing your code and that it works well in conjunction with the entire contract flow which is explained in the list above. Also, please note that you should not create a test for each of the items in the above list. This list indicates with each of its items the flow that must contain the only test that you must create to verify that the code you made works. You can also create more than 1 test if necessary, but if you do, you must justify why.

⚠️ **Important**: Please define a clear name for the test so that the purpose of the test is clearly understood.

## Recommendation:

Stellar people have in their discord a channel called “stella-help”, in that channel you can ask your technical questions about Stellar and its libraries (including the “soroban_sdk” library we use in the contract). This bot can help you a lot to solve your issues. Just remember that before submitting your query you must add the word “stella” at the beginning of the query. Otherwise the bot will not answer you.
The Stellar discord where you can find this channel is the following: [Stellar Discord](https://discord.gg/stellardev)

### ⚠️ **Please follow the guidelines for requesting an issue, launching commits and describing PR's. Otherwise they will be ignored.** ⚠️

### PR DESCRIPTION
**Pull request by coxmars**
<p align="center"> CLR-S (2) </p>

# Pull Request | Trustless Work

## 1. Issue Link

- Closes #24 

---

## 2. Brief Description of the Issue

The escrow contract needed to be updated with two new functions to handle dispute resolution and changing the dispute flag. 

---

## 3. Changes Made

- Added the change_dispute_flag function to allow the dispute resolver to set the dispute_flag property of an escrow to true, indicating that a dispute has been initiated.
- Modified the resolving_disputes function (previously named refund_remaining_funds) to allow the dispute resolver to refund the client and release funds to the service provider when a dispute has been resolved. 
- Implemented the necessary validations and error handling for both functions.
- Added tests to ensure all the flow is working as expected.
---

## 4. Evidence After Solution

image 

---

### CODE REVIEW

**Comment by coxmars** [comment]
Hi @armandocodecr @JoelVR17 this one is ready to be reviewed 🫡

**Comment by armandocodecr** [comment]
Hi @coxmars !

The overall code looks very good. I only have the following observations:

1. The escrow balance should be obtained using the method “balance” of the variable “usdc_client” to which you should pass the address of the escrow contract. In fact, the “balance” property should not be part of the escrow properties. This is something we will fix after the ODHACK.
2. The validation that only the dispute resolver can execute the “change_dispute_flag” function should be removed. This was a last minute change we made the day we uploaded the issues.
3. Please remove all comments in the “contract.rs” file. Only keep the comments that you consider strictly necessary due to code that can be complex to understand. This is to manage a better readability of the code.

**Review by armandocodecr — CHANGES_REQUESTED** [review]
My general comment I have left in the previous commentary. :)

**Comment by coxmars** [comment]
Hi @armandocodecr changes applied 🫡

**Comment by armandocodecr** [comment]
Thank you for your contribution @coxmars ! 🔥

**Pull request merged**
