### PR TITLE
Improve project structure 

### LINKED ISSUE #31: smart contract: Improve project structure and clean the code
## Description:

We need to improve the project folder structure and do some refactoring of the code if necessary.

## Requirements:

They should study and analyze the project and consequently leave us their proposals in their requests to improve the structure of the project's folders. In addition, they should include refactorings that they see necessary in the code. 

**👀 We will read and study your proposals and the best proposal will be assigned the issue for further development. 👀**

## Important:

You must make sure that the project continues to function exactly as it did before the changes were made. To ensure this, the tests should still be successful when you run the “cargo test” command.

## Recommendation:

Stellar people have in their discord a channel called “stella-help”, in that channel you can ask your technical questions about Stellar and its libraries (including the “soroban_sdk” library we use in the contract). This bot can help you a lot to solve your issues. Just remember that before submitting your query you must add the word “stella” at the beginning of the query. Otherwise the bot will not answer you.
The Stellar discord where you can find this channel is the following: [Stellar Discord](https://discord.gg/stellardev)

### ⚠️ **Please follow the guidelines for requesting an issue, launching commits and describing PR's. Otherwise they will be ignored.** ⚠️

### PR DESCRIPTION
**Pull request by ikemHood**
<p align="center"> CLR-S (2) </p>

# Pull Request | Trustless Work

## 1. Issue Link

- Closes #31

---

## 2. Brief Description of the Issue

Refactored contract code, and improved project folder structure.
---

## 3. Changes Made

- Improved project structure

---

## 4. Evidence After Solution

Test results after refactoring

Screenshot 2024-12-15 at 1 58 00 PM
---

## 5. Important Notes

- Concerns are now separated in folders.
- Major code logics are in folder `core`

### CODE REVIEW

**Review by armandocodecr — CHANGES_REQUESTED** [review]
Please make your changes in the default branch of the repository which is called “develop”. Your changes were applied to the “main” branch.

**Comment by armandocodecr** [comment]
Hi @ikemHood ! are you planning to finish the issue? I ask to know because otherwise I need to assign it to another dev.

**Comment by ikemHood** [comment]
Yes.

Had to close because I was developing on main branch.

Should create a new PR before morning.

**Comment by armandocodecr** [comment]
Okay, understood. Thanks for letting me know

**Pull request closed without merging**
